name: Deploy Pages
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3   # 新增，配置 Pages 环境

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # 更新成 v2
        with:
          path: Skywalker-Design  # 这里是你的网页文件夹

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2   # 更新成 v2
